//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymDetailsEntities : DbContext
    {
        public GymDetailsEntities()
            : base("name=GymDetailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<history_equipment> history_equipment { get; set; }
        public virtual DbSet<history_fees> history_fees { get; set; }
        public virtual DbSet<history_instructor> history_instructor { get; set; }
        public virtual DbSet<history_member> history_member { get; set; }
        public virtual DbSet<instructor> instructors { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<fee> fees { get; set; }
        public virtual DbSet<member> members { get; set; }
    }
}
