//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructor
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> contactno { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dateofjoining { get; set; }
        public Nullable<int> schedule { get; set; }
        public Nullable<int> salary { get; set; }
    }
}
