//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> amount { get; set; }
    }
}
