//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public string Code { get; set; }
        public string Title { get; set; }
        public decimal HourlyRate { get; set; }
        public decimal BasicSalary { get; set; }
    }
}
